### ISSUE TITLE
软件运行问题

### ISSUE THREAD

**Issue by BNS136** [Leon406/lanzou-gui#6]
![Uploading IMG_20230923_002434.jpg…]()
![Uploading IMG_20230923_002449.jpg…]()
一双击应用程序就出现这个问题，不知道是怎么回事，请问您能解答一下吗？
谢谢！

**Comment by BNS136** [comment]
![IMG_20230923_002434](https://github.com/Leon406/lanzou-gui/assets/110545950/7bc00ba6-c397-4fcb-af12-2b7b24da81b1)
![IMG_20230923_002449](https://github.com/Leon406/lanzou-gui/assets/110545950/4f02d535-3950-46cc-9839-4765d47a2a0f)
不知道为什么上面那个问题的两个图片裂开了

**Comment by Leon406** [comment]
不清楚, 如果是win7系统话, 大概率是兼容问题
