### ISSUE TITLE
无法正常生成exe程序

### ISSUE THREAD

**Issue by KINGOFKUN** [Leon406/lanzou-gui#7]
汇编工具：PyCharm
解析器下载完毕，在PyCharm运行程序可以正常显示和运行。
运行 buildWindows.bat 生成 exe程序，打开提示 Traceback (most recent call last): File "main.py", line 5, in <module> ModuleNotFoundError: No module named 'PyQt6'
将以前文件的PyQt6  复制到 _internal 后 提示 Traceback (most recent call last):  File "main.py", line 5, in <module>ImportError: DLL load failed while importing QtWidgets: 找不到指定的模块。
补齐到 _internal 后还提示这个信息。
然后我把以前老版本的所有文件都放到  _internal 再把新生成的放到  _internal 外的根目录打开，不显示，我删除了一些文件 python3.dll 放这个dll 就不显示 不放就报错 找不到指定模块。
作者大佬能否给个生成和环境配置的截图，或者作出一些说明，我在百度上找到的都是程序调试过程中出现找不到指定模块的，挠头。

**Comment by Leon406** [comment]
安装下依赖
pip install -r requirements.txt
